# Generated by Django 4.2.10 on 2024-02-17 05:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental_app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='rental_price',
            new_name='rental_price_per_day',
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='maximum_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='number_of_players',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('planned_return_date', models.DateTimeField(verbose_name='Planned Return Date')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_rental_app.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_rental_app.boardgame'),
        ),
    ]
