# Generated by Django 4.2.10 on 2024-02-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental_app', '0003_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='actual_return_date',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='planned_return_date',
        ),
    ]
