# Generated by Django 4.2.10 on 2024-02-26 08:32

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental_app', '0004_rename_actual_return_date_rental_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='maximum_age',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='max_duration',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='min_duration',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='minimum_age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='number_of_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rental_price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
