# Generated by Django 4.2.10 on 2024-02-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental_app', '0005_remove_boardgame_deposit_remove_boardgame_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='temp_slug',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
