# Generated by Django 4.2.10 on 2024-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rental_app', '0007_rename_temp_slug_boardgame_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
